name: "Get JOSM plugin dependencies"
description: "Get JOSM plugin dependencies"
inputs:
  plugin-dir:
    description: "The plugin directory"
  josm-revision:
    description: "The built JOSM revision. Must be built in a previous step"
  josm-test-revision:
    description: "The JOSM revision that the tests will run against"
  plugin-jar-name:
    description: "The name of the plugin jar. If not preset, defaults to repo name."

# Don't forget to remove fetch dependency when we can move to node18 (or later)
runs:
  using: "node16"
  main: "dist/index.js"
