name: "Ant setup"
description: "Setup ant"
inputs:
  ant-version:
    type: string
    default: 1.10.12
outputs:
  ant-home:
    value: ${{ steps.set-ant-home.outputs.ant-home }}

runs:
  using: "composite"
  steps:
  - name: Cache ant
    id: cache-ant
    uses: actions/cache@v3.0.0
    with:
      path: |
        josm/tools/apache-ant-${{ inputs.ant-version }}
      key: apache-ant-2-${{ inputs.ant-version }}

  - name: Set ANT_HOME
    id: set-ant-home
    run: |
      ANT_HOME="apache-ant-${{ inputs.ant-version }}"
      echo "export ANT_HOME=\"${ANT_HOME}\"" >> $GITHUB_ENV
      echo "export PATH=\"${ANT_HOME}\":${PATH}" >> $GITHUB_ENV
      echo "::set-output name=ant-home::${ANT_HOME}"
    shell: bash

  - name: Install Ant ${{ inputs.ant-version }}
    id: install-ant
    if: steps.cache-ant.outputs.cache-hit != 'true'
    run: |
      if [ ! -d josm/tools ]; then mkdir -p josm/tools; fi
      if [ ! -f josm/tools/${{ env.ANT_HOME }}-bin.tar.gz ]; then
        curl -o josm/tools/${{ env.ANT_HOME }}-bin.tar.gz https://downloads.apache.org/ant/binaries/${{ env.ANT_HOME }}-bin.tar.gz
      fi
      tar zxf josm/tools/${{ env.ANT_HOME }}-bin.tar.gz
    shell: bash

  - name: Ant diagnostics
    run: |
      ls
      ${{ env.ANT_HOME }}/bin/ant -diagnostics
    shell: bash
