name: "Checkstyle"
description: "Read Checkstyle and add annotations"
inputs:
  pathTrim:
    required: false
    description: "The path separator elements to remove from the front of a checkstyle path. Defaults to the number of parent components of the path that the action is run in."
  file:
    required: true
    description: The checkstyle file to parse and upload

runs:
  using: "node16"
  main: "dist/index.js"
