name: "JOSM Build"
description: "Build the appropriate JOSM jar and test files"
inputs:
  josm-revision:
    default: ''
    description: JOSM revision to use to build against, '' is current svn head, 'latest' is current latest, 'tested' is current tested, and 'rNUMBER' is for specific revisions
    required: false
outputs:
  josm-revision:
    description: The actual JOSM revision built. Useful for tested, latest, and '' josm-revision inputs.
  josm-test-revision:
    description: The actual JOSM test revision built. This is almost always the current SVN head.
runs:
  using: 'node16'
  main: 'dist/index.js'
