name: Publish reports
on:
  workflow_call

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: Ant reports for JOSM plugin ${{ github.event.repository.name }}
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          report_paths: 'josm/plugins/${{ github.event.repository.name }}/**/test/report/TEST*.xml'
